name: Lint

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/lint.yml'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy
    
    - name: Run Ruff
      run: |
        echo "Running Ruff linter..."
        ruff check . --statistics || true
        echo ""
        echo "Ruff check completed. To fix auto-fixable issues locally, run: ruff check . --fix"
    
    - name: Run MyPy
      run: |
        echo "Running MyPy type checker..."
        mypy . --ignore-missing-imports --no-error-summary || true
        echo ""
        echo "MyPy check completed."
    
    - name: Check critical issues
      run: |
        echo "Checking for critical issues..."
        # Count undefined names (F821)
        UNDEFINED_COUNT=$(ruff check . --select F821 --format=json | jq length 2>/dev/null || echo "0")
        if [ "$UNDEFINED_COUNT" -eq "0" ]; then
          echo "✅ No undefined names found"
        else
          echo "⚠️  Found $UNDEFINED_COUNT undefined name issues:"
          ruff check . --select F821 --no-fix || true
          echo ""
          echo "These are critical issues that should be fixed before merging."
        fi
        
        echo ""
        echo "=== Summary ==="
        echo "To run linting locally:"
        echo "  ruff check . --statistics"
        echo "To fix auto-fixable issues:"
        echo "  ruff check . --fix"